### PR TITLE
Cache for search query

### PR DESCRIPTION
**Pull request by dethi**
Same features as the Swift API Client.

* Disabled by default.
* Simple setup: `[myIndex enableSearchCache];`
* Auto-remove expired cache (Garbage Collection like)
* Configurable expiring time interval (default to 2 min)
* Cache search query only

cc @redox @speedblue

### CODE REVIEW

**Comment by dethi** [comment]
Ping

**Comment by vvo** [comment]
maybe @Nagriar can have a look (good commiter on the project).

**Comment by Nagriar** [comment]
Looks cool for me :+1:

**Comment by speedblue** [comment]
Yes very nice, good job @dethi

**Comment by speedblue** [comment]
@dethi I let you do the merge :)

**Pull request merged**
