### PR TITLE
Optional parameters

### PR DESCRIPTION
**Pull request by Nagriar**
Some query parameters can be defined in the index settings, we shouldn't use the default value to decide if we need to send an parameter or not.

### CODE REVIEW

**Comment by dethi** [comment]
I think you shouldn't expose all this new properties to the user. He will be confused, especially when using the autocomplete.
Like: *"wut!? which one should I use? synonyms or synonymsSet??"*

**Comment by Nagriar** [comment]
I didn't find a clean way to make them private, do you have an idea?

**Comment by dethi** [comment]
You can use ivar instead of property (http://www.benjaminloulier.com/posts/private-properties-methods-and-ivars-in-objective-c/)

**Comment by Nagriar** [comment]
@dethi With that we should be good :)

**Comment by dethi** [comment]
LGTM :+1:

**Comment by Nagriar** [comment]
Fire!

**Pull request merged**
