### PR TITLE
Enable support for advancedSyntax in query

### PR DESCRIPTION
**Pull request by apassant**
Enable support for advancedSyntax in query

### CODE REVIEW

**Comment by holgersindbaek** [comment]
Damn good timing. I just realized I need this. Can someone merge?!

**Comment by dethi** [comment]
LGTM, cc @Nagriar

**Comment by Nagriar** [comment]
It's good but we have an issue with the default value of query parameters, since you can activate the advancedSyntax in the index settings. With this implementation you can't disable the advancedSyntax.

I'll need to rewrite this part to send the parameters when they're set.

Let's merge it anyway! Thx @apassant

**Comment by apassant** [comment]
@Nagriar Ah sorry I haven't seen that! I guess that changing line 81 _advancedSyntax = NO; to  = nil, and updating the test in line 447 accordingly would make it work as planned? I can resubmit another pull request if you prefer.

**Comment by Nagriar** [comment]
If you can do that it'll be perfect :)

**Comment by apassant** [comment]
@Nagriar I've noticed that this issue already happens for the boolean values that can be setup in the index, but updated on the query:
- ignorePlural
- typosOnNumericTokens

They can only be set to False in the lib, so if the default value is False on the index, there's no way to set it to True at query time.

Fixing that would require to change BOOL values by NSNumber so that we can distinguish between TRUE/FALSE and nil (aka default index value). I'm happy to do the change for those 2 and advancedSyntax, but that won't be backwards compatible with the current lib.

Opinions?

**Comment by Nagriar** [comment]
Hi @apassant,

It could be better to override the getter and setter to keep the backwards compatibility and then in the setter to put the right corresponding numeric value.

What do you think?

**Pull request merged**
